version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cys-sam-typescript"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3u8ft82oapr5"
s3_prefix = "cys-sam-typescript"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
